version: '3.4'

services:

  nginx:
    image: nginx:1.15-alpine
    ports:
      - "8080:80"
    volumes:
      - ./etc/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    depends_on:
      - php

  php:
    build:
      context: ./etc/dev/php/
    ports:
      - "2323:22"
    volumes:
      - .:/app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=api
      - MYSQL_DATABASE=wayne_lifts
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
